version: '3'
services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api:app --reload --workers 1 --host 0.0.0.0 --port 8000